Filename bug, toggle running time entry handling and rounding
DisyInformationssysteme/toggl-jira-integration pull request #4
Opened 2021-01-28 08:23 UTC by RockItDown

Hey, 

I found a key error, for the 'filename' field in config.
Furthermore the time_entry[duration] always indicates whether the most recent time entry is still running.
That's the reason I moved it out of the loop. The behavior should not change, but is is clearer and more readable, imo.
One commit addresses a more personal problem I found with rounding up all the time. I think this could be excluded, as it is more personal preference.

Hope you find it helpful,
Jonas

2021-03-22 07:29 UTC, stranljip requested changes
Bitte die Rundung wieder anpassen wir im Kommentar angemerkt.

2021-03-22 07:29 UTC, stranljip commented on processTimeTrackingEntries.py
> +            duration = str(round(duration / (float(60) * 15)) * 15) + "m"
Nein, das behalten wir so bei. Der Hintergrund ist eine Entscheidung, dass noicht feingranularer als 15min geloggt werden soll, d.h. jede angefangenen 15min zählen. Da sich das hier auf gruppierte EInträge bezieht, ist das eh ein Kompromiss. Bitte also ursprünglichen Zustand mit math.ceil beibehalten.

2021-03-22 07:32 UTC, stranljip commented
Generelle Anmerkungen noch:
* erstmal Danke für den PR :-) 
* Du hast hier in einem PR drei verschiedene Sachen drin. Für den Review und auch für Änderungen die für einzelene Teiule angefrag werden wäre es besser, sowas zukünftig in mehrere PRs aufzuteilen

2021-07-23 12:46 UTC, RockItDown commented
The last commit should resolve at least one issue you had with the PR.
Hope it can be merged now :)

2021-11-03 10:23 UTC, stranljip requested changes

2021-11-03 10:23 UTC, stranljip commented on processTimeTrackingEntries.py
> -
Sorry - den PR hatte ich nicht mehr auf dem Zettel.

Ich kann nicht ganz nachvollziehen, warum das Skript komplett abbrechen soll wenn ein Eintrag noch läuft. Kannst du den Teil bitte in einen eigenen PR rausziehen? Dann kann ich den Bug mit dem Dateinamen mergen und das andere können wir uns dann ansehen.

2021-11-11 14:20 UTC, merged